# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MaLiangDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # MaLiang drawing library
  pod 'MaLiang'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set Swift version to avoid future language mode errors
      config.build_settings['SWIFT_VERSION'] = '5.0'
      # Suppress specific warnings
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      # Set minimum deployment target
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
